apiVersion: v1
kind: Pod
metadata:
  name: apiservice
  namespace: compression-namespace
  labels:
    app: apiservice
spec:
  containers:
    - name: api-service-container
      image: mt194/api-service
      ports:
        - containerPort: 8080
          name: http-web-svc
      resources:
        requests:
          memory: '64Mi'
          cpu: '250m'
        limits:
          memory: '128Mi'
          cpu: '500m'
---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
  namespace: compression-namespace
spec:
  selector:
    app: apiservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: huffman-compression
  namespace: compression-namespace
spec:
  completions: 4 # must match the env variable WORKER_NUMBER
  parallelism: 4 # must match the env variable WORKER_NUMBER
  completionMode: Indexed
  backoffLimitPerIndex: 0
  template:
    metadata:
      labels:
        app: huffman-compression
    spec:
      restartPolicy: Never
      containers:
        - name: huffman-compression
          image: mt194/huffman-compression
          imagePullPolicy: Always
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: huffman-compression
  namespace: compression-namespace
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: huffman-compression
---

